### ISSUE TITLE
Remarques suite à test utilisateur

### ISSUE THREAD

**Issue by simkim** [laclassealamaison-org/laclassealamaison#103]
- [x]  les infos flash s'affichent sous la forme de bouton ou de texte sans formatage suivant les pages, s'est confus 
- [ ]  Le lien du mail de confirmation doit rediriger sur la page de connexion avec le mail pré-rempli
- [x]  sur certaines pages il faut changer "0/15" vers "0/15 élèves" pour rendre plus clair.
- [x]  Si je parcours le catalogue sans avoir ajouté d'enfant, il doit me proposer d'en rajouter en cas de besoin.
- [x]  Revoir les marges des cartes sur les différentes pages en différente résolution (au moins nexus 5x et ipad (portrait / paysage)
- [x]  Aligner en bas les boutons de carte dans le catalogue
- [x]  Supprimer le commentaire de la session
- [x] Placer au milieu la boite de cours sur formulaire d'inscription
- [x] Revoir le formulaire de connexion/création de compte
- [x] Sur l'espace professeur, utiliser la même logique que l'espace parent : l'index des cours envoie sur la vue show qui montre un bouton d'edition, la liste des sessions du cours et un bouton d'ajout de session
- [x] Dans l'édition d'un cours, traduire le label description en "Thématique (en une phrase)"

**Comment by Pil0u** [comment]
Au-delà du pré-remplissage de l'email en cliquant sur le lien de confirmation, il serait intéressant d'avoir un flash qui précise "Votre compte est confirmé. Vous pouvez vous connecter"
