### ISSUE TITLE
Inciter les profs à la planification des cours

### ISSUE THREAD

**Issue by lcalmtest** [laclassealamaison-org/laclassealamaison#131]
Pour l'instant lorsque le prof crée son cours, il n'y a d'incitation à planifier le cours dans la foulée.
Ajouter un lien une fois le cours créé pour planifier des sessions

**Comment by simkim** [comment]
L'application redirige maintenant sur la planification d'une session après la création d'un cours. On peut toujours revenir au cours en cliquant "Retour au cours"
