### ISSUE TITLE
Création de groupe

### ISSUE THREAD

**Issue by lcalmtest** [laclassealamaison-org/laclassealamaison#133]
@simkim 
Création de groupe pour que des enseignants ou animateurs puissent faire du live avec seulement leurs élèves ou enfants

**Comment by simkim** [comment]
- [ ] Un professeur peut créer des groupes (CRUD)
- [ ] Un professeur peut restreindre une session à un groupe
- [ ] Un professeur pour donner le lien du groupe à un utilisateur par un canal tiers pour l'inviter
- [ ] Un élève peut s'inscrire à un groupe en connaissant son lien.

@chou34500 peux tu proposer des maquettes ?

**Comment by simkim** [comment]
@cyrildotcc j'attends donc vos écrans pour implémenter la fonction.
