### ISSUE TITLE
Aide aux devoirs

### ISSUE THREAD

**Issue by lcalmtest** [laclassealamaison-org/laclassealamaison#76]
Ouvrir la plateforme sur une aide aux devoirs pour les CM1-CM2 dans un premier temps afin de voir le résultat.
Permettre aux enfants de poser leurs questions dans un tchat après avoir sélectionner leurs niveaux ainsi que la matière concernée

**Comment by cyrildotcc** [comment]
Ajouter un bouton "Rejoindre le chat pour l'aide aux devoirs" sur les pages des classes du CP au CM2.
